### ISSUE TITLE
[router] Error when serving connection

### ISSUE THREAD

**Issue by subhashdasyam** [tpbowden/swarm-ingress-router#26] opened 2016-11-25 04:24 UTC
I am seeing the following error in router logs, due to this the domain1.com isn't working properly. It has frequent disconnects

Pasting the log info

**2016/11/25 04:18:12 error when serving connection "10.255.0.25:8443"<->"10.255.0.5:50751": error when reading request headers: need more data: cannot find trailing lf. buf="GET /assets/dabblet.css HTTP/1.1\r\nHost: domain1.com\r\nCookie: sessionid=\".eJy9mFtz27gVx1PHiddyLtu9NE2v224vyqaWABC8IG3aJvY63tjrOLaZKJ3JaEAANGlJpCCSTtwZzrQv_TLth-rn6NMeUKTrnW4aSTvZJ5MgjHP0Owfn_IG_"..."=sso.domain.com%2Fauth%2Fform%2Flogin.html%2C100%2C100%2C804%2C1440%2C804%2C1920%2C1200%2C1%2CP; AMCVS_B8D07FF4520E94C10A490D4C%40AdobeOrg=1; AMCV_B8D07FF4520E94C10A490D4C%40AdobeOrg=-227196251%7C"
2016/11/25 04:18:13 Registering service for domain1.com
2016/11/25 04:18:13 Registering service for domain2.com
2016/11/25 04:18:13 Registering service for domain3.com
2016/11/25 04:18:13 Registering service for domain4.com
2016/11/25 04:18:13 Routes updated**

**Comment by tpbowden** [comment] 2016-11-25 09:13
looks like this is being caused by your headers being too big for the buffer allocated by fasthttp. I think it is related to this issue: valyala/fasthttp/issues/173

**Comment by larryboymi** [comment] 2016-12-13 16:10
I'm also experiencing this error, when trying to do auth via kerberos.... I send in a somewhat large header (3-4Kb) and I receive `error when serving connection \"10.255.0.12:8080\"\u003c-\u003e\"10.255.0.2:51628\": error when reading request headers: need more data: cannot find trailing lf.`.

**Comment by tpbowden** [comment] 2016-12-13 17:12
Have you tried rebuilding the router and running against the latest version of fasthttp? There is a chance this issue has been fixed by now. I will have a go at the weekend if I get time.

**Comment by larryboymi** [comment] 2016-12-13 17:38
I'm trying to rebuild the router with a larger fixed ReadBufferSize in the constructor... not sure that's working yet. I'll keep you posted.

**Comment by tpbowden** [comment] 2016-12-13 17:53
The default buffer size is 4096 bytes which would explain the issue you're having - i guess 8KB would be enough? That's the default in Apache I believe

**Comment by larryboymi** [comment] 2016-12-13 18:38
I used [1Mb](https://github.com/ocelotconsulting/swarm-ingress-router/blob/master/server/server.go#L110) just to make sure it was a non-factor, and it worked for my use case (proxied kerberos)! 

Going to set it back down to 8KB, and if it works, leave it at that.

**Comment by tpbowden** [comment] 2017-01-13 14:20
This is fixed now that max header size is configurable.

**Closed by tpbowden** 2017-01-13 14:20 UTC
